---
title: "Campsite"
author: "Sarah Gillespie, Berry Williams, Eva Putman"
date: "2019-05-15"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r StartingItems, message=FALSE}
library(tidyverse)
library(macleish)
library(sf)
library(leaflet)
library(dplyr)
library(lwgeom)
```

```{r Code, message=FALSE}

my_points <- tribble(
  ~point, ~lat, ~lon,
  "A",  42.448483, -72.675119)

#icons from https://www.nps.gov/maps/tools/symbol-library/

new_campsite_icon <- icons(
  iconUrl = "https://www.nps.gov/maps/tools/symbol-library/assets/img/campsite-black-22.svg")

stream_x_icon <- icons(
  iconUrl = "https://www.nps.gov/maps/tools/symbol-library/assets/img/wading-black-22.svg"
)

macleish_layers %>%
  pluck("trails") %>%
  st_length()

trails <- macleish_layers %>%
  pluck("trails") %>%
  mutate(computed_length = st_length(geometry))

macleish_layers %>%
  pluck("boundary") %>%
  st_area()

proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

boundaries_aea <- macleish_layers %>%
  pluck("boundary") %>%
  st_transform(proj4_aea)

macleish_layers %>%
  pluck("trails") %>%
  st_intersects(pluck(macleish_layers ,"streams"))

macleish_layers %>%
  pluck("trails") %>%
  st_crosses(pluck(macleish_layers, "streams"))

trail_stream_xings <- macleish_layers %>%
  pluck("trails") %>%
  st_intersection(pluck(macleish_layers, "streams"))

leaflet() %>%
  addTiles() %>%
  addPolylines(data = pluck(macleish_layers, "streams")) %>%
  addPolylines(data = pluck(macleish_layers, "trails"), color = "brown") %>%
  addMarkers(data = st_cast(trail_stream_xings, "POINT"), icon = stream_x_icon, popup = ~name)

stream_buffer <- macleish_layers %>%
  pluck("streams") %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist = 10) %>%
  st_transform(4326)

leaflet() %>%
  addTiles() %>%
  addPolylines(data = pluck(macleish_layers, "streams"), 
               weight = 1, color = "black") %>%
  addPolygons(data = stream_buffer) %>% 
  addMarkers(data = my_points, icon = new_campsite_icon, popup = "Proposed campsite")

  
```



^[[Github Repository](https://github.com/SarahGillespie/sds192-mp3)
]